name: Auto Update JSON

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate update.json
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION_NAME="${TAG#v}"
          VERSION_CODE=$(date +%Y%m%d%H%M)

          # 获取 Release 简介，并做 JSON 转义
          LOG=$(printf '%s' "${{ github.event.release.body }}" | jq -Rs .)

          URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/update_${VERSION_NAME}.apk"

          cat > update/update.json <<EOF
          {
            "versionCode": $VERSION_CODE,
            "versionName": "$VERSION_NAME",
            "updateLog": $LOG,
            "downloadUrl": "$URL"
          }
          EOF

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add update/update.json
          git commit -m "chore: update ${{ github.event.release.tag_name }}" || echo "No changes"
          git push
